### ISSUE TITLE
Public Port

### ISSUE THREAD

**Issue by Lite5h4dow** [HaNdTriX/next-electron-server#3]
Hi, again. 
Just wondering if it would be possible to use a public port? because if so, it would really help for my use case as i actually want to expose a page to the localhost on a port

**Comment by HaNdTriX** [comment]
I am not sure if I understand your question correctly.

You can configure the port of the next.js devserver using the settings of 

- [Next.js CLI](https://nextjs.org/docs/api-reference/cli#development)
- and [This module](https://github.com/HaNdTriX/next-electron-server#-port)

If you want to handle requests from outside electron use [electrons protocol handlers](https://www.electronjs.org/docs/api/app#appsetasdefaultprotocolclientprotocol-path-args) or [node.js http module](https://nodejs.org/api/http.html#http_http_createserver_options_requestlistener). Both approaches are out of the scope of this module. [This code might help you implementing it](https://github.com/HaNdTriX/next-electron-server/blob/master/index.js#L63-L103).

Hope that helps ;)

**Comment by Lite5h4dow** [comment]
how would i forward page from the custom protocol to localhost then?

**Comment by Lite5h4dow** [comment]
ok, so i forwarded the file itself since i couldnt find a way to do it using the protocol (i just dont understand it). however i get errors that i dont get when this is displayed to the electron window.

here is Pixijs running successfully in the electron window. this is what im expecting when i serve the file directly to the browser
![image](https://user-images.githubusercontent.com/18059545/110867346-7566ca80-82be-11eb-8021-9dda93793388.png)

however this is what i get when i serve the plain html file via the network and injest it with chrome:
![image](https://user-images.githubusercontent.com/18059545/110867514-c676be80-82be-11eb-8d3c-797dd96b47b2.png)

this is my index.js.
```js
const { join } = require("path");
const { BrowserWindow, app } = require("electron");
const serveNext = require("next-electron-server");
const http = require("http");
const fs = require("fs");

serveNext("nuzlocke://app");

app.on("ready", async () => {
  const mainWindow = new BrowserWindow({
    width: 1000,
    height: 600,
    webPreferences: {
      preload: join(__dirname, "preload.js"),
    },
  });

  mainWindow.loadURL("nuzlocke://app");
});

const server = http.createServer((req, res) => {
  res.writeHead(200, { "content-type": "text/html" });

  fs.createReadStream(join(app.getAppPath(), "./out/index.html")).pipe(res);
});

server.listen(8585);

app.on("window-all-closed", app.quit);
```
