### ISSUE TITLE
Usage with nextron

### ISSUE THREAD

**Issue by niteshbalusu11** [HaNdTriX/next-electron-server#8]
Hey!

https://github.com/saltyshiomix/nextron/issues/247

I saw this issue you had opened on nextron to use next-electron-server instead of electron-serve.
I personally have a lot of issues with electron-serve, I switched to using next-electron-server and I see my a lot of my issues have been fixed, however when I start the app in dev mode, it's constantly throwing this error in the console log.

```
websocket.js?2e1e:45 WebSocket connection to 'wss://app/_next/webpack-hmr' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
```

I am on the latest version of nextron which uses nextjs 12.

Can you help with this?

**Comment by HaNdTriX** [comment]
closing in favour of https://github.com/HaNdTriX/next-electron-server/issues/7
